#!/bin/bash
#
# Shows how to attach a file descriptor to a file
#	Reads stdin, or, the file on the command line
#
# Kurt Schmidt
# NOV 2016
#
# GNU bash, version 4.3.46(1)-release (x86_64-pc-linux-gnu), on
# Linux 4.4.0-36-generic #55-Ubuntu x86_64 GNU/Linux
#

if [ -n "$1" -a -f "$1" -a -r "$1" ] ; then
	exec 0<"$1"  
fi

while read line ; do
	echo $line
done

